#+TITLE: Emacs Vim Git -- Command Line Git Goodies
#+AUTHOR: Jonathan Lai

* Session Talk 10:15 - 11:00

** Introduction
If one thing you learn in this session, take note of this website
http://awesome.re

Jonathan Lai
@jonlai
jonathanlai@stanford.edu
https://itunconference.stanford.edu/emacs-vim-git-command-line-goodies

Stanford Graduate School of Education IT (gseit.stanford.edu) at the CERAS building near Green Library and the Law School

Background: Biology, Education, Tech

Very much into tech for the open source / academic / sharing ethos.

** Interest in Command Line tools background
What's your background in working with the terminal.
Console / Bash, git, emacs, vim?

emacs, vim, git

what do you already know about them.

what topics would you like covered.

What do you want to get out of this session

** awesome website resources

http://awesome.re

https://github.com/emacs-tw/awesome-emacs

https://github.com/mhinz/vim-galore

Websites for emacs, vim (neovim), plugins, plugin repositories

https://github.com/git-tips/tips
https://github.com/tj/git-extras

https://asconfluence.stanford.edu/confluence/display/GSEIT/How+to+use+git
I can share this internal page later

** emacs and vim with git tools
Magit - emacs
Fugitive - vim

Other various plugins for them both. The awesome websites link to a lot of resources.

Alternatively, use pure git tools like a

- git blame
- git delete-branch (tj git extras)
- git count (tj git extras)
- git info (tj git extras)

-tig

** git tools plus
Using git, magit in emacs, git with vim and tj/git-extras
git diffs, git blame,
git stash viewage
git log viewage, beautify git log

Gotta navigate around emacs more efficiently, and this is how.

** Other cool command line tools with text editor integration 

fzf

ag (like grep but faster)

** More vim and emacs goodness

cat file.txt | vi -

g blame file.txt

** init-last-minute-touches
Here are some last minute touches.

** Other / Misc

Org mode - what I used for this presentation

More plugins and emacs tools in my emacs config on github
https://github.com/agsdot/.emacs.d

Pandoc, org to markdown to others

ix.io

gist.github.com

I'll post and share these notes.


** Questions and Answers
10:45 and onwards

Feel free to followup via email / twitter / github / slack etc