#+TITLE: Emacs Vim Git -- Command Line Git Goodies
#+AUTHOR: Jonathan Lai

* Session Talk 10:15 - 11:00

** Introduction
If one thing you learn in this session, take note of this website
http://awesome.re

Jonathan Lai
@jonlai
jonathanlai@stanford.edu
https://itunconference.stanford.edu/emacs-vim-git-command-line-goodies

Stanford Graduate School of Education IT (gseit.stanford.edu) at the CERAS building near Green Library and the Law School

Background: Biology, Education, Tech

Very much into tech for the open source / academic / sharing ethos.

** Interest in Command Line tools background
What's your background in working with the terminal.
Console / Bash, git, emacs, vim?

emacs, vim, git

what do you already know about them.

what topics would you like covered.

What do you want to get out of this session

** awesome website resources

http://awesome.re

https://github.com/emacs-tw/awesome-emacs

https://github.com/mhinz/vim-galore

Websites for emacs, vim (neovim), plugins, plugin repositories

https://github.com/git-tips/tips
https://github.com/tj/git-extras

https://asconfluence.stanford.edu/confluence/display/GSEIT/How+to+use+git
I can share this internal page later

** init-navigation
Gotta navigate around emacs more efficiently, and this is how.

** init-vim
Lets add the awesome vim/modal editing keybindings. So much more fluid to edit with than emacs own.

** init-coding
Here we're going to make emacs a great coding environment.

** init-last-minute-touches
Here are some last minute touches.

** Other / Misc

Pandoc, org to markdown to others

ix.io

gist.github.com

I'll post and share these notes.


** Questions and Answers
10:45 and onwards