#+TITLE: Emacs Vim Git -- Command Line Git Goodies
#+AUTHOR: Jonathan Lai

* Emacs Init as an Org file

** Introduction
Jonathan Lai
@jonlai
jonathanlai@stanford.edu

Stanford Graduate School of Education IT (gseit.stanford.edu) at the CERAS building near Green Library and the Law School

Background: Biology, Education, Tech

Very much into tech for the open source / academic / sharing ethos.

** Interest in Command Line tools background
What's your background in working with the terminal.
Console / Bash, git, emacs, vim?

What do you want to get out of this session

** init-aesthetics
Lets make emacs look and behave better.

loreimasdfsdf sadf

** init-navigation
Gotta navigate around emacs more efficiently, and this is how.

** init-vim
Lets add the awesome vim/modal editing keybindings. So much more fluid to edit with than emacs own.

** init-coding
Here we're going to make emacs a great coding environment.

** init-last-minute-touches
Here are some last minute touches.


** Other / Misc

Pandoc, org to markdown to others
